pypy 2.5.0

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -30,11 +30,11 @@ if [ ! "$SKIP_INSTALL" ]; then
     mkdir -p .heroku/python
 
     #curl https://lang-python.s3.amazonaws.com/$STACK/runtimes/$PYTHON_VERSION.tar.gz -s | tar zxv -C .heroku/python &> /dev/null
-    if [[ $? != 0 ]] ; then
-      puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
-      puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
-      exit 1
-    fi
+    #if [[ $? != 0 ]] ; then
+    #  puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
+    #  puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
+    #  exit 1
+    #fi
 
   bpwatch stop install_python
 
